%% Exact linearization of the Simulink model model
%
% This MATLAB script is the command line equivalent of the exact
% linearization tab in linear analysis tool with current settings.
% It produces the exact same linearization results as hitting the Linearize button.

% MATLAB(R) file generated by MATLAB(R) 9.10 and Simulink Control Design (TM) 5.7.
%
% Generated on: 22-Oct-2023 18:34:16

%% Specify the model name
model = 'model';

%% Specify the analysis I/Os
% Get the analysis I/Os from the model
io = getlinio(model);

%% Specify the operating point
% Use the model initial condition
op = operpoint(model);


%% Create the options
opt = linearizeOptions('StoreAdvisor',true);

%% Linearize the model
[sys,~,info] = linearize(model,io,op,opt);
advisor = info.Advisor;

%% Plot the resulting linearization
step(sys)
tf(sys)

%% Get Linearization Diagnostics

% The section below is equivalent to creating the queries from
% the advisor tab and generating the diagnostics for use in
% the command line.

query1 = linqueryIsOnPath & linqueryHasDiagnostics;
query2 = linqueryIsOnPath & linqueryIsBlockSubstituted;
query3 = linqueryIsOnPath & linqueryHasZeroIOPair;
query4 = linqueryIsOnPath;

query1.QueryType = 'Diagnostics on Path';
query1.Description = '(On Linearization Path AND Has Diagnostics)';
query2.QueryType = 'Substitutions on Path';
query2.Description = '(On Linearization Path AND Block Substituted)';
query3.QueryType = 'Zero I/O Pair on Path';
query3.Description = '(On Linearization Path AND Has Zero I/O Pair)';
query4.QueryType = 'All Blocks on Path';
query4.Description = 'On Linearization Path';

advisor_advise = advise(advisor);

advisor1 = find(advisor,query1);
advisor2 = find(advisor,query2);
advisor3 = find(advisor,query3);
advisor4 = find(advisor,query4);

